Repository pivotal-cf/docs-scheduler, pull requests merged in 2020-07, with the labels that each got.

#40 Should remove the release note - Remove “test-scheduler-diagnostics” …
  docs-content/release-notes.html.md.erb
Labels: scheduled

#41 Update a subnet for the Scheduler Errands
  docs-content/installing.html.md.erb
Labels: unscheduled

#42 Document create-job memory and disk limit flags
  docs-content/using-jobs.html.md.erb
Labels: in progress
